### ISSUE TITLE
insert.js -- missing 2 /'s

### ISSUE THREAD

**Issue by todk** [pofider/node-simple-odata-server#17]
lines 42 and 43 are missing a / between **cfg.serviceUrl** and **req.params.collection**

current lines 42 and 43:
`entity["@odata.id"] = cfg.serviceUrl + req.params.collection + "/('" + entity._id + "')";
            entity["@odata.editLink"] = cfg.serviceUrl + req.params.collection + "/('" + entity._id + "')";
`

suggested (works for me anyway)
`entity["@odata.id"] = cfg.serviceUrl + "/" + req.params.collection + "/('" + entity._id + "')";
            entity["@odata.editLink"] = cfg.serviceUrl + "/" + req.params.collection + "/('" + entity._id + "')";
`

otherwise, this is nifty server.  thanks!

**Comment by pofider** [comment]
Thank you, I believe this was fixed in #24
