### ISSUE TITLE
Unable to filter on nested property in a collection

### ISSUE THREAD

**Issue by PremeraSOAPOC** [pofider/node-simple-odata-server#18]
I tried a couple of ways to query on nested property: 
$expand=addresses($filter=city eq 'Seattle')
$expand=addresses($filter=addresses/city eq 'Seattle')
$filter=addresses/city eq 'Seattle'

However it errors out with http 500 error.

**Comment by pofider** [comment]
I'm afraid that expand feature is not implemented and it is not on my current schedule. However anyone is welcome to send PR adding it.
