### ISSUE TITLE
Add my own database?

### ISSUE THREAD

**Issue by retorquere** [pofider/node-simple-odata-server#29]
I have a postgresql database with JSONB documents. Is it possible to use this inside node-simple-odata-server via a translation layer of some kind?

**Comment by pofider** [comment]
You would need to implement the `update`, `remove`, `query`, and `insert` handlers like we do here
https://github.com/pofider/node-simple-odata-server/blob/master/lib/nedbAdapter.js

I do something similar in [this package](https://github.com/jsreport/jsreport-sql-store), but unfortunately I'm too busty to provide something you would be able to use right away. Hopefully you or someone else will be able to contribute it.
