### ISSUE TITLE
Geospatial support?

### ISSUE THREAD

**Issue by carrbrpoa** [pofider/node-simple-odata-server#30]
Hello,

Found [this](http://www.odata.org/blog/geospatial-data-support-in-odata/) in OData archives.
Question: what is the support provided by node-simple-odata-server?

Thanks!

**Comment by pofider** [comment]
No support, unfortunately. 
We extend the library only for our internal needs in [jsreport](https://jsreport.net/) and geospatial is not something we would require. However PRs are welcome.
