### ISSUE TITLE
TypeError: simpleOdataServer.adapter is not a function

### ISSUE THREAD

**Issue by xjuhu** [pofider/node-simple-odata-server#32]
Tested in my own system, as well as on npm.runkit, always getting same error:
TypeError: simpleOdataServer.adapter is not a function

Demo-Code from runkit:

```
var mongoClt = require('mongodb').MongoClient;
var simpleOdataServer = require("simple-odata-server");
var Adapter = require('simple-odata-server-mongodb');
var url = "127.0.0.1:27017";

mongoClt.connect(url, function(err, db) {
    simpleOdataServer.adapter(Adapter(function(cb) { cb(err, db); })); 
});
```

**Comment by pofider** [comment]
See the example.
https://github.com/pofider/node-simple-odata-server#get-started

```js
var odataServer = ODataServer("http://localhost:1337")
    .model(model)
    .adapter(Adapter(function(es, cb) { cb(null, db)}));
```

**Comment by xjuhu** [comment]
Sorry, got my example from your suggestion:

The mongo adapter can be used as

var Adapter = require('simple-odata-server-mongodb')
MongoClient.connect(url, function(err, db) {
	odataServer.adapter(Adapter(function(cb) { 
		cb(err, db.db('myodatadb')); 
	})); 
});

Using mongodb, I have no model of data, because the documents stored are very different in structure and content. How to use this without a applying a model?

**Comment by pofider** [comment]
Unfortunately the model is required.

**Comment by xjuhu** [comment]
Ok, I see, this approach will not end up in a working stack for me. 
Thank you for your replies, anyway.
